query FullMediaCard(
    $id: Int,
    $type: MediaType,
    $innerListsPerPage: Int,
    $innerListsPage: Int,
    $voiceActorsLanguage: StaffLanguage
) {
    Media(id: $id,type: $type) {
        id
        type
        format
        status(version: 2)
        description
        season
        seasonYear
        episodes
        duration
        chapters
        volumes
        countryOfOrigin
        isLicensed
        source(version: 3)
        hashtag
        updatedAt
        bannerImage
        genres
        synonyms
        averageScore
        meanScore
        popularity
        isLocked
        trending
        favourites
        isFavourite
        isFavouriteBlocked
        siteUrl
        autoCreateForumThread
        isRecommendationBlocked
        isReviewBlocked
        modNotes
        isAdult
        title {
            ... mediaTitle
        }
        startDate {
            ... fuzzyDate
        }
        endDate {
            ... fuzzyDate
        }
        trailer {
            ... mediaTrailer
        }
        coverImage {
            ... mediaCoverImage
        }
        tags {
            ... mediaTag
        }
        relations {
            ... basicMediaRelationQuery
        }
        characters(perPage: $innerListsPerPage, page: $innerListsPage) {
            edges {
                role
                node {
                    ... basicCharacter
                }
                voiceActors(language: $voiceActorsLanguage) {
                    ... basicStaff
                }
            }

        }
        staff(perPage: $innerListsPerPage, page: $innerListsPage) {
            ... basicStaffQuery
        }
        studios {
            ... basicStudioQuery
        }
        nextAiringEpisode {
            ... nextAiringEpisode
        }
        externalLinks {
            ... mediaExternalLink
        }
        recommendations(perPage: $innerListsPerPage, page: $innerListsPage) {
            ... basicRecommendationsQuery
        }
        reviews(perPage: $innerListsPerPage, page: $innerListsPage) {
            ... basicReviewQuery
        }
        stats {
            ... basicStats
        }
        airingSchedule(perPage: $innerListsPerPage, page: $innerListsPage) {
            edges {
                node {
                    ... nextAiringEpisode
                }
            }
        }
        streamingEpisodes {
            ... mediaStreamingEpisode
        }
        rankings {
            ... mediaRanking
        }
    }
}

